### PR TITLE
RecMEAElectrode implementation

### PR DESCRIPTION
**Pull request by espenhgn**
class similar to LFPy.RecMEAElectrode with tests. 
Some required changes:

- upstream changes to parent class RecExtElectrode described in #34 applies here

- public method `test_cell_extent` is now hidden. 

- added method `distort_cell_geometry` from `LFPy.Cell` to class RecMEAElectrode (won't rely on CellGeometry-class methods which may be simulator dependent)

- skipped reimplementing `test_slice_shift_invariance_pointsource` from LFPy as it required LFPy simulation output. Potential errors will be captured by LFPy itself in the future

### CODE REVIEW

**Comment by espenhgn** [comment]
Hi @torbjone. Could you please take a quick look at this PR in particular? don't think I broke anything.

**Comment by espenhgn** [comment]
I'll add a working docstring example and update the other.

**Review by torbjone — APPROVED** [review]
I have not tested the code, but it looks good to me.

One question: what is the point of the factor 10 on line 934:
z=np.array([[0, 0], [0, 0], [0, 0], [0, 0]]) * 10,

**Comment by espenhgn** [comment]
> One question: what is the point of the factor 10 on line 934:
> z=np.array([[0, 0], [0, 0], [0, 0], [0, 0]]) * 10,

Should've been a + 10 I guess! 

I'll have to do some conflict fixing before merging this into master.

**Pull request merged**
